In [2]:
import pandas as pd

In [3]:
data=pd.read_table('http://bit.ly/movieusers')
data.head()

   1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [4]:
data.tail()

          1|24|M|technician|85711
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

In [5]:
data=pd.read_table('http://bit.ly/movieusers',sep ='|')
data.head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [6]:
data=pd.read_table('http://bit.ly/movieusers',sep ='|',header = None)
data.head()

   0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [7]:
Header_Columns = ["index","age","department","postal_code"]
data=pd.read_table('http://bit.ly/movieusers',sep ='|',header = None, names=Header_Columns)
data.head()

   index age  department postal_code
1     24   M  technician       85711
2     53   F       other       94043
3     23   M      writer       32067
4     24   M  technician       43537
5     33   F       other       15213

In [8]:
user_info = pd.read_csv("http://bit.ly/uforeports")

In [9]:
type(user_info)

pandas.core.frame.DataFrame

In [10]:
user_info.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [11]:
user_info["City"].head()

0                  Ithaca
1             Willingboro
2                 Holyoke
3                 Abilene
4    New York Worlds Fair
Name: City, dtype: object

In [12]:
user_info.City.tail()

18236     Grant Park
18237    Spirit Lake
18238    Eagle River
18239    Eagle River
18240           Ybor
Name: City, dtype: object

In [13]:
user_info["Colors Reported"].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Colors Reported, dtype: object

In [14]:
user_info.shape

(18241, 5)

In [15]:
user_info.City + user_info.State

0                      IthacaNY
1                 WillingboroNJ
2                     HolyokeCO
3                     AbileneKS
4        New York Worlds FairNY
                  ...
18236              Grant ParkIL
18237             Spirit LakeIA
18238             Eagle RiverWI
18239             Eagle RiverWI
18240                    YborFL
Length: 18241, dtype: object

In [17]:
user_info.City + ", " + user_info.State

0                      Ithaca, NY
1                 Willingboro, NJ
2                     Holyoke, CO
3                     Abilene, KS
4        New York Worlds Fair, NY
                   ...
18236              Grant Park, IL
18237             Spirit Lake, IA
18238             Eagle River, WI
18239             Eagle River, WI
18240                    Ybor, FL
Length: 18241, dtype: object

In [18]:
user_info["Location"] = user_info.City +", "+ user_info.State
user_info.head()

,City,Colors Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [19]:
user_info.to_csv("./newfile.csv")

In [20]:
newfile = pd.read_csv("./newfile.csv")
newfile.head()

,Unnamed: 0,City,Colors Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [21]:
newfile.describe()

         Unnamed: 0
count  18241.000000
mean    9120.000000
std     5265.867466
min        0.000000
25%     4560.000000
50%     9120.000000
75%    13680.000000
max    18240.000000

In [22]:
newfile.dtypes

Unnamed: 0          int64
City               object
Colors Reported    object
Shape Reported     object
State              object
Time               object
Location           object
dtype: object

In [23]:
newfile.describe(include="object")

,City,Colors Reported,Shape Reported,State,Time,Location
count,18215,2882,15597,18241,18241,18215
unique,6475,27,27,52,16145,8028
top,Seattle,RED,LIGHT,CA,11/16/1999 19:00,"Seattle, WA"
freq,187,780,2803,2529,27,187

In [27]:
newfile[:5]

,Unnamed: 0,City,Colors Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [30]:
newfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       18241 non-null  int64
 1   City             18215 non-null  object
 2   Colors Reported  2882 non-null   object
 3   Shape Reported   15597 non-null  object
 4   State            18241 non-null  object
 5   Time             18241 non-null  object
 6   Location         18215 non-null  object
dtypes: int64(1), object(6)
memory usage: 997.7+ KB

In [28]:
newfile.columns

Index(['Unnamed: 0', 'City', 'Colors Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='object')

In [37]:
newfile.rename(columns={'Colors Reported': 'Colors_Reported'})

,Unnamed: 0,City,Colors_Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"
...,...,...,...,...,...,...,...
18236,18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,"Grant Park, IL"
18237,18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,"Spirit Lake, IA"
18238,18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,"Eagle River, WI"
18239,18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,"Eagle River, WI"
18240,18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59,"Ybor, FL"

In [38]:
newfile.columns

Index(['Unnamed: 0', 'City', 'Colors Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='object')

In [39]:
newfile.rename(columns={'Colors Reported': 'Colors_Reported'}, inplace=True)

In [40]:
newfile.head()

,Unnamed: 0,City,Colors_Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [41]:
newfile.columns

Index(['Unnamed: 0', 'City', 'Colors_Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='object')

In [42]:
newfile_column = ["index","City","Colors Reported","Shape Reported","State","Time","Location"]

In [43]:
newfile.columns=newfile_column

In [58]:
newfile.head()

,index,City,Colors Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [59]:
new_column = ["City","Colors Reported","Shape Reported","State","Time"]

In [60]:
ufo = pd.read_csv("http://bit.ly/uforeports",names=new_column,header=0)

In [61]:
ufo[:1]

     City Colors Reported Shape Reported State            Time
0  Ithaca             NaN       TRIANGLE    NY  6/1/1930 22:00

In [62]:
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='object')

In [63]:
ufo.columns = ufo.columns.str.replace(' ','_')

In [64]:
ufo.columns

Index(['City', 'Colors_Reported', 'Shape_Reported', 'State', 'Time'], dtype='object')

## Reomve Columns

In [65]:
#ufo.drop('Colors_Reported',axis=1,inplace=True) #axis = 1 for columns

In [67]:
ufo.drop(['Colors_Reported',"City"],axis=1,inplace=True)

KeyError: "['Colors_Reported', 'City'] not found in axis"

In [68]:
ufo.head()

  Shape_Reported State             Time
0       TRIANGLE    NY   6/1/1930 22:00
1          OTHER    NJ  6/30/1930 20:00
2           OVAL    CO  2/15/1931 14:00
3           DISK    KS   6/1/1931 13:00
4          LIGHT    NY  4/18/1933 19:00

## Remove Rows

In [69]:
ufo.drop([0,1,2],axis=0,inplace=True)

In [70]:
ufo.head()

  Shape_Reported State             Time
3           DISK    KS   6/1/1931 13:00
4          LIGHT    NY  4/18/1933 19:00
5           DISK    ND  9/15/1934 15:30
6         CIRCLE    CA   6/15/1935 0:00
7           DISK    MI   7/15/1936 0:00

## Sort a Pandas

In [72]:
movies=pd.read_csv('http://bit.ly/imdbratings')

In [73]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [74]:
movies.title.sort_values()

542     (500) Days of Summer
5               12 Angry Men
201         12 Years a Slave
698                127 Hours
110    2001: A Space Odyssey
               ...
955         Zero Dark Thirty
677                   Zodiac
615               Zombieland
526                     Zulu
864                    [Rec]
Name: title, Length: 979, dtype: object

In [75]:
movies.title.sort_values(ascending=False)

864                    [Rec]
526                     Zulu
615               Zombieland
677                   Zodiac
955         Zero Dark Thirty
               ...
110    2001: A Space Odyssey
698                127 Hours
201         12 Years a Slave
5               12 Angry Men
542     (500) Days of Summer
Name: title, Length: 979, dtype: object

In [76]:
movies.sort_values("title")

,star_rating,title,content_rating,genre,duration,actors_list
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
201,8.1,12 Years a Slave,R,Biography,134,"[u'Chiwetel Ejiofor', u'Michael Kenneth Willia..."
698,7.6,127 Hours,R,Adventure,94,"[u'James Franco', u'Amber Tamblyn', u'Kate Mara']"
110,8.3,2001: A Space Odyssey,G,Mystery,160,"[u'Keir Dullea', u'Gary Lockwood', u'William S..."
...,...,...,...,...,...,...
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
615,7.7,Zombieland,R,Comedy,88,"[u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha..."
526,7.8,Zulu,UNRATED,Drama,138,"[u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac..."
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."

In [77]:
movies.sort_values(['content_rating','duration'])

,star_rating,title,content_rating,genre,duration,actors_list
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
272,8.1,The Killing,APPROVED,Crime,85,"[u'Sterling Hayden', u'Coleen Gray', u'Vince E..."
703,7.6,Dracula,APPROVED,Horror,85,"[u'Bela Lugosi', u'Helen Chandler', u'David Ma..."
612,7.7,A Hard Day's Night,APPROVED,Comedy,87,"[u'John Lennon', u'Paul McCartney', u'George H..."
...,...,...,...,...,...,...
387,8.0,Midnight Cowboy,X,Drama,113,"[u'Dustin Hoffman', u'Jon Voight', u'Sylvia Mi..."
86,8.4,A Clockwork Orange,X,Crime,136,"[u'Malcolm McDowell', u'Patrick Magee', u'Mich..."
187,8.2,Butch Cassidy and the Sundance Kid,NaN,Biography,110,"[u'Paul Newman', u'Robert Redford', u'Katharin..."
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"
649,7.7,Where Eagles Dare,NaN,Action,158,"[u'Richard Burton', u'Clint Eastwood', u'Mary ..."

In [78]:
boolean = []
for length in movies.duration:
    if length >= 200:
        boolean.append(True)
    else:
        boolean.append(False)

In [79]:
boolean[0:3]

[False, False, True]

In [80]:
len(boolean)

979

## Speed Way to Filter

In [81]:
is_long=pd.Series(boolean)
is_long.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [82]:
is_long = movies.duration>=200
is_long.head()

0    False
1    False
2     True
3    False
4    False
Name: duration, dtype: bool

In [83]:
movies[is_long]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [84]:
movies.loc[movies.duration >= 200 ,"genre"]

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

## Multiple filter

In [85]:
movies[(movies.duration >=  200)&(movies.genre =="Drama")]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."