In [2]:
import numpy as np

In [5]:
vec = np.linspace(0,10,num=25)
mat = vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [8]:
i = np.identity(3,dtype = "float32")
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [9]:
np.random.random((3,3))

array([[0.45173919, 0.66137329, 0.85489808],
       [0.50618118, 0.62662098, 0.27316357],
       [0.23590993, 0.72419827, 0.17724994]])

In [10]:
np.random.randint(0,11,(5,5))

array([[ 9,  4,  2,  2,  6],
       [10,  5,  1,  1,  9],
       [ 9,  2,  0,  5, 10],
       [10,  3,  0,  1,  1],
       [10,  1,  0,  7,  6]], dtype=int32)

In [16]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((5,3))
np.savez('test_np.npz',ones_mat = mat_1,zeros_mat=mat_2)

In [17]:
with np.load('test_np.npz') as file:
    mat_1 = file['ones_mat']
    mat_2 = file["zeros_mat"]

In [19]:
print(mat_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [20]:
m1 = np.array([[1,2,3],
              [4,5,6]])
m2 = np.array([[7,8,9],
               [0,0,0]])

In [21]:
mat_s = np.vstack((m1,m2))

In [22]:
mat_s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [23]:
mat_s = np.hstack((m1,m2))

In [24]:
mat_s

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 0, 0]])

In [25]:
s= 4
v = np.array([2,4,3,4,10])
v == s

array([False,  True, False,  True, False])

In [26]:
v1 = np.array([2,4,3,4,10])
v2 = np.array([2,4,3,4,5])
v1 == v2

array([ True,  True,  True,  True, False])

In [28]:
v1 = np.array([0,4,3,4,10])
np.all(v1>=1)

np.False_

In [30]:
np.any(v1 >=1)

np.True_

In [31]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,4,10])
np.isclose(v1,v2 , atol  = 1)

array([ True,  True, False,  True, False])

In [32]:
np.allclose(v1,v2 , atol  = 1)

False

In [33]:
v = np.array([2,4,3,4,10])
condition = v>=4
print(condition)

[False  True False  True  True]

In [34]:
v = np.array([2,4,3,4,10])
condition = v>=4
new_arr = np.where(condition,-1,v)
print(new_arr)

[ 2 -1  3 -1 -1]

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\aldawliahasbat\onedrive - faculty of engineering (kafr elsheikh university)\desktop\depi_ais2_g3_ml-1\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('test.csv')
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011
10,11,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.90,NaN,299494.17,299494.17,2011
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011
12,13,EDWARD HARRINGTON,EXECUTIVE CONTRACT EMPLOYEE,294580.02,0.00,0.00,NaN,294580.02,294580.02,2011
13,14,JOHN MARTIN,DEPARTMENT HEAD V,271329.03,0.00,21342.59,NaN,292671.62,292671.62,2011
14,15,DAVID FRANKLIN,"BATTALION CHIEF, (FIRE DEPARTMENT)",174872.64,74050.30,37424.11,NaN,286347.05,286347.05,2011
15,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,NaN,286213.86,286213.86,2011
16,17,AMY HART,DEPARTMENT HEAD V,268604.57,0.00,16115.86,NaN,284720.43,284720.43,2011
17,18,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
18,19,MARTY ROSS,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.63,69626.12,38115.47,NaN,276434.22,276434.22,2011
19,20,ELLEN MOFFATT,ASSISTANT MEDICAL EXAMINER,257510.59,880.16,16159.50,NaN,274550.25,274550.25,2011
20,21,VENUS AZAR,ASSISTANT MEDICAL EXAMINER,257510.48,0.00,16679.79,NaN,274190.27,274190.27,2011
21,22,JUDY MELINEK,ASSISTANT MEDICAL EXAMINER,257510.44,377.21,15883.56,NaN,273771.21,273771.21,2011
22,23,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
23,24,VICTOR WYRSCH,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.63,77896.14,24083.86,NaN,270672.63,270672.63,2011
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140546.86,97868.77,31909.28,NaN,270324.91,270324.91,2011
25,26,GREGORY SUHR,CHIEF OF POLICE,256470.41,0.00,11522.18,NaN,267992.59,267992.59,2011
26,27,JOHN HANLEY,"CAPTAIN, FIRE SUPPRESSION",92080.80,40008.00,133695.76,NaN,265784.56,265784.56,2011
27,28,RAYMOND GUZMAN,"BATTALION CHIEF, (FIRE DEPARTMENT)",168692.59,80706.88,16063.99,NaN,265463.46,265463.46,2011
28,29,DENISE SCHMITT,DEPUTY CHIEF III (POLICE DEPARTMENT),261717.60,0.00,2357.00,NaN,264074.60,264074.60,2011
29,30,MONICA FIELDS,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",246225.60,0.00,15140.54,NaN,261366.14,261366.14,2011
30,31,HARLAN KELLY-JR,EXECUTIVE CONTRACT EMPLOYEE,234325.02,0.00,25972.64,NaN,260297.66,260297.66,2011
31,32,DAVID SHINN,DEPUTY CHIEF III (POLICE DEPARTMENT),254027.63,0.00,5899.48,NaN,259927.11,259927.11,2011
32,33,GARY AMELIO,DEPARTMENT HEAD V,248895.70,0.00,10789.18,NaN,259684.88,259684.88,2011
33,34,JOHN TURSI,"INSPECTOR III, (POLICE DEPARTMENT)",104861.39,50227.61,103499.39,NaN,258588.39,258588.39,2011
34,35,JOSE VELO,"BATTALION CHIEF, (FIRE DEPARTMENT)",177781.25,59924.97,20658.00,NaN,258364.22,258364.22,2011
35,36,KHOA TRINH,ELECTRONIC MAINTENANCE TECHNICIAN,101953.20,139102.95,16483.94,NaN,257540.09,257540.09,2011
36,37,SUSAN CURRIN,"ADMINISTRATOR, SFGH MEDICAL CENTER",245124.44,0.00,12000.00,NaN,257124.44,257124.44,2011
37,38,JAMES BOSCH,"INSPECTOR III, (POLICE DEPARTMENT)",110661.20,31162.04,111446.20,NaN,253269.44,253269.44,2011
38,39,JONES WONG,LIEUTENANT III (POLICE DEPARTMENT),132202.26,52648.92,67083.83,NaN,251935.01,251935.01,2011
39,40,BRENDAN WARD,"BATTALION CHIEF, (FIRE DEPARTMENT)",147158.85,64985.85,39540.46,NaN,251685.16,251685.16,2011

In [5]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011

In [6]:
df.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
35,36,KHOA TRINH,ELECTRONIC MAINTENANCE TECHNICIAN,101953.20,139102.95,16483.94,NaN,257540.09,257540.09,2011
36,37,SUSAN CURRIN,"ADMINISTRATOR, SFGH MEDICAL CENTER",245124.44,0.00,12000.00,NaN,257124.44,257124.44,2011
37,38,JAMES BOSCH,"INSPECTOR III, (POLICE DEPARTMENT)",110661.20,31162.04,111446.20,NaN,253269.44,253269.44,2011
38,39,JONES WONG,LIEUTENANT III (POLICE DEPARTMENT),132202.26,52648.92,67083.83,NaN,251935.01,251935.01,2011
39,40,BRENDAN WARD,"BATTALION CHIEF, (FIRE DEPARTMENT)",147158.85,64985.85,39540.46,NaN,251685.16,251685.16,2011

In [8]:
s = pd.Series([1,2,3,4],index=["A",'B','C','D'])
s

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
data = [[1,444,"abc"],
        [1,555,'def'],
        [3,666,"ghi"],
        [4,777,"xyz"]]
df = pd.DataFrame(data,columns=["idx","id","name"])
display(df)

   idx   id name
0    1  444  abc
1    1  555  def
2    3  666  ghi
3    4  777  xyz

In [13]:
df.dtypes

idx      int64
id       int64
name    object
dtype: object

In [14]:
df["id"].dtype

dtype('int64')

In [15]:
df["id"] = df["id"].astype("category")
df.dtypes

idx        int64
id      category
name      object
dtype: object

In [16]:
cols = ["idx","id"]
df[cols] = df[cols].astype("category")
df.dtypes

idx     category
id      category
name      object
dtype: object

In [ ]:
cat_cols = ["idx","name"]
num_cols = ['id']
df[cat_cols] = df[cat_cols].astype("category")
df.dtypes

ValueError: Cannot cast object dtype to int64

In [18]:
df.tail(2)

  idx   id name
2   3  666  ghi
3   4  777  xyz

In [19]:
df.describe()

        idx   id name
count     4    4    4
unique    3    4    4
top       1  444  abc
freq      2    1    1

In [23]:
data = [[1,444,"abc"],
        [1,555,'def'],
        [3,666,"ghi"],
        [4,777,"xyz"]]
df = pd.DataFrame(data,columns=["idx","id","name"])
cat_cols = ["idx","name"]
df[cat_cols] = df[cat_cols].astype("category")
df.describe(include="category")

        idx name
count     4    4
unique    3    4
top       1  abc
freq      2    1

In [24]:
df["id"].unique()

array([444, 555, 666, 777])

In [25]:
df["id"].nunique()

4

In [26]:
df.columns

Index(['idx', 'id', 'name'], dtype='object')

In [28]:
data = [[1,444,"abc"],
        [1,555,'def'],
        [3,666,"ghi"],
        [4,777,"xyz"]]
df = pd.DataFrame(data,columns=["idx","id","name"])

In [29]:
df["id"].max()

np.int64(777)

In [30]:
df["name"].max()

'xyz'

In [31]:
df["id"].min()

np.int64(444)

In [32]:
df["name"].min()

'abc'

In [33]:
df["name"].idxmin()

0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idx     4 non-null      int64
 1   id      4 non-null      int64
 2   name    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [35]:
d = df["id"].value_counts()

In [36]:
d

id
444    1
555    1
666    1
777    1
Name: count, dtype: int64

In [37]:
df["id"].sum()

np.int64(2442)

In [38]:
df.max()

idx       4
id      777
name    xyz
dtype: object

In [39]:
df["id"].values

array([444, 555, 666, 777])

In [40]:
df.values

array([[1, 444, 'abc'],
       [1, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 777, 'xyz']], dtype=object)

In [42]:
df.replace(666,888)

   idx   id name
0    1  444  abc
1    1  555  def
2    3  888  ghi
3    4  777  xyz

In [43]:
df.replace({444:"randa",777:444})

   idx     id name
0    1  randa  abc
1    1    555  def
2    3    666  ghi
3    4    444  xyz

In [44]:
def duplicated(x):
    return x*2


df["id"].apply(duplicated)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [45]:
df["id"].apply(lambda x:x*2)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [ ]:
df.idx # one word or without spaces

0    1
1    1
2    3
3    4
Name: idx, dtype: int64

In [49]:
df.iloc[2,1]

np.int64(666)

In [50]:
df.iloc[:,0:2]

   idx   id
0    1  444
1    1  555
2    3  666
3    4  777

In [55]:
df['new_col'] = df.name + df.name
df

   idx   id name new_col
0    1  444  abc  abcabc
1    1  555  def  defdef
2    3  666  ghi  ghighi
3    4  777  xyz  xyzxyz

In [56]:
df.drop("new_col",axis=1)

   idx   id name
0    1  444  abc
1    1  555  def
2    3  666  ghi
3    4  777  xyz

In [64]:
new_row = {"id":9 , "idx":99 , "name":"welcome"}
pd.concat([df ],[ pd.DataFrame(new_row)])

ValueError: If using all scalar values, you must pass an index

In [66]:
null = df.isnull()
null

     idx     id   name  new_col
0  False  False  False    False
1  False  False  False    False
2  False  False  False    False
3  False  False  False    False

In [70]:
pd.DataFrame(null.sum()).T

   idx  id  name  new_col
0    0   0     0        0

In [72]:
def ch_null(df):
    null = df.isnull()
    return pd.DataFrame(null.sum()).T

In [73]:
df.dropna()

   idx   id name new_col
0    1  444  abc  abcabc
1    1  555  def  defdef
2    3  666  ghi  ghighi
3    4  777  xyz  xyzxyz

In [74]:
df.dropna(subset=["idx"])

   idx   id name new_col
0    1  444  abc  abcabc
1    1  555  def  defdef
2    3  666  ghi  ghighi
3    4  777  xyz  xyzxyz

In [77]:
mean = df.id.mean()
df_name = df.name.fillna(value = mean)
df

   idx   id name new_col
0    1  444  abc  abcabc
1    1  555  def  defdef
2    3  666  ghi  ghighi
3    4  777  xyz  xyzxyz